# Generated by Django 6.1.1 on 2026-09-23 23:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('ano_publicacao', models.IntegerField()),
                ('tipo_acervo', models.CharField(choices=[('DIGITAL', 'Digital'), ('FISICO', 'Físico')], default='FISICO', max_length=10)),
                ('categoria', models.CharField(choices=[('000', '000 – Generalidades e Informação: Obras gerais, enciclopédias, jornais e biblioteconomia.'), ('100', '100 – Filosofia e Psicologia: Ética, lógica e investigações sobre a mente humana.'), ('200', '200 – Religião e Teologia: Mitologia, teologia e estudos sobre crenças e religiões.'), ('300', '300 – Ciências Sociais e Direito: Política, economia, sociologia, educação e leis.'), ('400', '400 – Linguística e Idiomas: Gramáticas, dicionários e estudos de línguas.'), ('500', '500 – Ciências Puras (Exatas e Naturais): Matemática, física, química, biologia e astronomia.'), ('600', '600 – Ciências Aplicadas (Tecnologia): Medicina, engenharia, agricultura e administração.'), ('700', '700 – Artes e Recreação: Pintura, música, arquitetura, esportes e lazer.'), ('800', '800 – Literatura: Poesia, romances, contos, crônicas e crítica literária.'), ('900', '900 – História e Geografia: Biografias, viagens e acontecimentos históricos')], default='000', max_length=3)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='acervo.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_patrimonio', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EMPRESTADO', 'Emprestado'), ('MANUTENCAO', 'Em Manutenção')], default='DISPONIVEL', max_length=20)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='acervo.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Empréstimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.now)),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao_real', models.DateField(blank=True, null=True)),
                ('multa_calculada', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('ativo', models.BooleanField(default=True)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.exemplar')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.membro')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO', max_length=20)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='acervo.livro')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.membro')),
            ],
        ),
    ]
